### ISSUE TITLE
Docker run fails : cannot load module redisgraph.so

### ISSUE THREAD

**Issue by schwab** [RedisLabs/redismod#1]
From a clean docker install I ran the steps as specified in the readme....
`
docker pull redislabs/redismod
docker run -p 6379:6379 redislabs/redismod`
which fails with: 
Can't load module from /usr/lib/redis/modules/redisgraph.so: server aborting

environment:
Ubuntu 18.04 with 
Docker version 18.09.0, build 4d60db4

is this docker image still valid?

**Comment by itamarhaber** [comment]
Hello @schwab 

Thanks for reporting the breakage - I can verify that this is caused by a missing libgomp dependency:

```
1:M 05 Dec 2018 15:35:16.838 # Module /usr/lib/redis/modules/redisgraph.so failed to load: libgomp.so.1: cannot open shared object file: No such file or directory
1:M 05 Dec 2018 15:35:16.838 # Can't load module from /usr/lib/redis/modules/redisgraph.so: server aborting
```

@jeffreylovitz @swilly22 got a quick fix?

**Comment by jeffreylovitz** [comment]
It looks like the `redismod` image is pointing to an outdated RedisGraph version.

The RedisGraph-specific Docker image shouldn't have this problem:
`docker run -p 6379:6379 -it --rm redislabs/redisgraph`

**Comment by itamarhaber** [comment]
Thanks for the fix @jeffreylovitz - I verified the latest image from Docker hub is indeed bootstrapping correctly, but please feel free to reopen @schwab if the issue isn't resolved for you.

**Comment by premosipalli** [comment]
change the path in the docker image to : /usr/lib/redis/modules/redisgears.so
